# Generated by Django 5.2 on 2025-05-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_staffrole_role_alter_staffrole_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport_series', models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('age', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Возраст')),
                ('staff_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='users.staffrole', verbose_name='Staff role')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('workplace', models.CharField(max_length=255, verbose_name='Место работы')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='uploads/questions/', verbose_name='Прикрепленный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания вопроса')),
                ('redirected', models.BooleanField(default=False, verbose_name='Перенаправлен')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorProfile.doctorprofile', verbose_name='Профиль врача')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
