# Generated by Django 5.2 on 2025-05-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_area', models.CharField(max_length=255, verbose_name='Территория страхования')),
                ('smo', models.CharField(max_length=255, verbose_name='СМО (страховая компания)')),
                ('policy_type', models.CharField(max_length=50, verbose_name='Тип полиса')),
                ('series', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('issue_date', models.DateField(verbose_name='Дата начала действия полиса')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия полиса')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_address', models.CharField(max_length=255, verbose_name='Адрес регистрации')),
                ('residential_address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', models.CharField(max_length=14, verbose_name='СНИЛС')),
                ('document_type', models.CharField(max_length=100, verbose_name='Тип документа (паспорт и т.д.)')),
                ('series', models.CharField(max_length=10, verbose_name='Серия')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='patients.patient')),
            ],
        ),
    ]
