# Generated by Django 5.2 on 2025-05-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы врача'),
        ),
    ]
