# Generated by Django 5.2 on 2025-05-11 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Системный администратор'), ('doctor', 'Врач'), ('support', 'Сопровождающий программы')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff roles'),
        ),
    ]
